version: '3'
services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - service1
      - service2
      - service3
  service1:
    build: ./microservices/service1
    ports:
      - "3001:3001"
  service2:
    build: ./microservices/service2
    ports:
      - "3002:3002"
  service3:
    build: ./microservices/service3
    ports:
      - "3003:3003"
